"""empty message

Revision ID: 69ae55b2764b
Revises: ba4fb616e298
Create Date: 2023-09-11 12:52:25.975675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69ae55b2764b'
down_revision = 'ba4fb616e298'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('imagem', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('servicos', schema=None) as batch_op:
        batch_op.drop_column('imagem')

    # ### end Alembic commands ###
