"""empty message

Revision ID: 6bb793e7211e
Revises: c79e2139fc3e
Create Date: 2023-09-10 20:28:11.283129

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6bb793e7211e'
down_revision = 'c79e2139fc3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conteudos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('conteudo', sa.String(length=1000), nullable=False))
        batch_op.drop_column('logradouro')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('conteudos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('logradouro', sa.VARCHAR(length=1000), nullable=False))
        batch_op.drop_column('conteudo')

    # ### end Alembic commands ###
