"""empty message

Revision ID: c79e2139fc3e
Revises: 6ae52b5f8f9d
Create Date: 2023-08-08 14:14:36.622010

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c79e2139fc3e'
down_revision = '6ae52b5f8f9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subtopicos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('subtopico_imagem', sa.String(length=100), nullable=False),
    sa.Column('subtopico_conteudo', sa.String(length=10000), nullable=False),
    sa.Column('subtopico_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['subtopico_id'], ['subconteudos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subtopicos')
    # ### end Alembic commands ###
